language: python

python:
  - "3.6"

install:
#  - pip install -r requirements.txt
  - pip install .
  - python setup.py install

script: pytest

branches:
  only:
  - develop
  - master

notifications:
  email: false


